### ISSUE TITLE
Spísať Prvú Verziu Katalógu Požiadaviek

### ISSUE THREAD

**Issue by Booqeefus** [TIS2024-FMFI/sailing-simulator#2]

**Comment by pavelpetrovic** [comment]
Dobrý deň, posielam prvú vlnu mojich komentárov ku KP, teším sa na ďalšiu verziu.
Pripomínam, že by nemalo ostať nič, na čom ste sa so zadávateľom dohodli a v dokumente to nie je zachytené.
A rovnako ak si predstavíte, aké všetky rozhodnutia budete musieť počas implementácie urobiť - radšej ich urobte teraz, zapíšte ich do KP, aby sa k nim zadávateľ vyjadril, aby ste to nemuseli potom meniť a zisťovať počas implementácie. Chýba tu toho ešte veľa.

do 1.1 by ste mohli pridať, že KP je zároveň záväznou dohodou medzi zadávateľom a vývojovým tímom o rozsahu funkcionality.

1.3. graficky zvýraznite pojmy (tučným alebo kurzívou)
"byt rýchli a obratný" => "byť rýchli a obratní"
AW a TW je tam 2x, napriek tomu to slovo "pocitový"
nie veľmi sedí. človek môže mať pocit, ale tu sa
zrejme myslí relatívny nameraný a nie len nejaký dojem.

skúsite použíť zarovnávanie na oba okraje (štýl justify)?

2.1. "ale aj ich postupné zdokonaľovanie v budúcnosti."
 budu sa v buducnosti zdokonalovat **preteky**?
 
 "Lode budú schopné merať AW, vizualizovať ho a následne prepočítať na TW. "
  => oni poznajú svoj vektor rýchlosti? odkiaľ? z GPS?
  a čo znamená "lode budú schopné"?  nejaký riadiaci
  algoritmus/skript, ktorý tam napíše používateľ?
  lebo inak simulátor pozná TW, takže by bolo zbytočné
  najskôr vypočítať AW a potom TW. nie je to zrozumiteľné.
 
 "Každá plachetnica bude plávať po trati určenej bojkami"
  => to sa týka iba jedného z dvoch druhov pretekov alebo oboch?
  prosím ak oboch, tak to zdôraznite a aj v tejto 2. časti
  by bolo dobre načrtnúť, aký je medzi nimi rozdiel, 
  lebo vôbec netuším - je to iba v tom na akom veľkom "území"
  to celé beží?
  
 "budú naznačovať lodiam" => to znie ako keby tam bola
 nejaká aktívna komunikácia medzi loďou a bójkou, ale
 ten, čo riadi loď má asi nejakú mapu pred sebou, nie?
 alebo to je na tých bójkach farebne znázornené a zistí
 to až keď ich opticky uvidí?
 
 3.1.1.2.  nerozumiem. chceli ste povedať, že poloha
 nastaviteľnej plachty má ovplyvňovať vzhľad lode v záberoch zo simulovaných kamier?
 
3.1.2. "prepočítavať ho" nie je jasné, čo znamená, že *loď* niečo prepočítava. loď je loď a nie kalkulačka.

3.1.4. ako bude používateľ riadiť kormidlo? bude tam mať zobrazený nejaké koleso, ktorým bude vedieť točiť, alebo nejaké tlačidlá myši, alebo klávesnicou? alebo rovno do textboxu zadá číslo? alebo aj viac z týchto možností? treba to uviesť.
to isté pre riadenie plachty.

5.1. dá sa frekvencia snapshotov nastaviť? Ako? v konfiguračnom súbore, alebo iba po spustení niekde v menu aplikácie?
v akokm formáte sa snapshot ukladá? je to textový súbor
v ktorom sú všetky záznamy z jednej lode? alebo pre každý
snapshot je nový subor? alebo to nakoniec bude jedno CSV so všetkými loďami z celej jazdy? Ako budú priradené jednotlivé
obrázkové súbory k tým snapshotom, aby sa to potom dalo
interpretovať?

3.1.5.1.3 budú vodné prúdy a vietor statické? nebudú sa vôbec meniť?

3.2.1. formulácii nerozumiem. toto znie, ako keby simulátor ponúkol iba dve fixné trate. ale je to v rozpore s 3.2.2

3.2.2.1 aký vplyv na simuláciu bude mať hĺbka vody?
  bude mať loď vo svojich parametroch určenú hĺbku svojho kýlu a v plyšej vode alebo na súši uviazne? nejaký iný vplyv?
  
3.2.2.2. bude mriežka vždy štvorcová alebo obdĺžniková, alebo môže byť aj iná? 

3.3.1.2. môže sa stať, že vietor bude silnejší ako kýl? má kýl udanú hmotnosť a hĺbku? a ak bude iba o málo silnejší, rozkýve to loď?

V druhej časti sa píše:
"Vstupom do systému bude súbor, na základe ktorého systém vygeneruje mapu." ale v tretej časti o tom nie je ani slovo, ale treba to tiež podrobne špecifikovať.

Podľa akého vzorca bude kormidlo upravovať smer lode?

Kde sa bude dať nastaviť "odpor vody"?

V tretej časti sa nič nepíše o tom, ako prebieha simulácia, akú funkcionalitu aplikácia poskytuje počas simulácie používateľovi? Len napríklad:
Môže sa napr. prepínať medzi kamerami? alebo naraz v rôznych oknách vidieť viac kamier? Beží v reálnom čase? Vždy? Nedá sa zrchliť? Dá sa pozastaviť? Keď sa prepína medzi loďami a nastavuje ich, môže vtedy pozastaviť simuláciu a potom ju zasa pustiť ďalej? 

Nebolo by namiesto "ortogonálnej kamery" jednoduchšie zobrazovať pozíciu lodí (ikoniek) na mape (aj s ich natočením plachiet a kormidla)
