### ISSUE TITLE
Druhé stretnutie s cvičiacím

### ISSUE THREAD

**Issue by Booqeefus** [TIS2024-FMFI/sailing-simulator#26]

**Comment by pavelpetrovic** [comment]
vsetci pritomni
cviciaci je prekvapeny, ze pocas riadenia plachetnice jachtar nevidi ziadne informacie, ziaden riadiaci panel. naozaj to zadavatel nechce?
posunul sa navrh UI az do fazy kontrola zadavatelom
tesime sa na kontrolu celeho navrhu buduci tyzden
a zaroven sa rozbieha implementacia
